---
abstract: 'tokenizer for OpenCorpora project'
author:
  - 'OpenCorpora.org team L<http://opencorpora.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::Number::Delta: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Lingua::RU::OpenCorpora::Tokenizer
name: Lingua-RU-OpenCorpora-Tokenizer
no_index:
  directory:
    - inc
    - share
    - t
requires:
  File::ShareDir: 0
  IO::Uncompress::Gunzip: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
