#!/bin/bash

#usage: bash tokenize_and_pos_tag_file path_to_training_file_directory 

FILES="$1"*
for f in $FILES
do

    if ! [[ $f == *tokenized* || $f == *postagged* || $f == *post_processed* || $f == *conll* || $f == *annotated* || $f == *~* ]]
    then
        originalfile=$f
        perl Lingua-RU-OpenCorpora-Tokenizer-0.03/tokenize "$f" "$f"_tokenized
        python "post_process_tokenization.py" "$f"_tokenized
        tree-tagger/bin/tree-tagger tree-tagger/russian.par "$f"_tokenized_post_processed "$f"_postagged "-token"
        python "convert_to_conll.py" "$f"_postagged
    fi
done


